const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const AUTH_ERROR = "AUTH_ERROR";

const SEND_MAIL = "SEND_MAIL";
const ALL_MAILS = "ALL_MAILS";
const MAIL_ERROR = "MAIL_ERROR";
const RESET_STATE = "RESET_STATE";
const GET_SEND_MAILS = "GET_SEND_MAILS";

export {
  AUTH,
  LOGOUT,
  AUTH_ERROR,
  SEND_MAIL,
  ALL_MAILS,
  MAIL_ERROR,
  RESET_STATE,GET_SEND_MAILS
};
